// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-comfort.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var MESSAGES = [
  "You don't have to have the words. Just being here is enough.",
  "Whatever you're carrying today, you don't have to carry it alone.",
  "Feelings are visitors. Let them sit with you; they will move on.",
  "You have survived every hard day so far. That is not nothing.",
  "Rest is not quitting. Slow is still forward.",
  "Someone would be glad you're still here. Including future you.",
  "It's okay if today was only about getting through it.",
  "Your pain is real, and it is not the whole of you."
];
var BREATHING = [
  "Find a comfortable seat and let your shoulders drop.",
  "Breathe in through your nose for 4 counts.",
  "Hold gently for 7 counts.",
  "Breathe out slowly through your mouth for 8 counts.",
  "Repeat 4 times. Notice how your body feels afterwards."
];
var get_comfort_default = defineTool({
  name: "get_comfort",
  title: "Get a comforting message",
  description: "Return a gentle, grounding message from purelisten, optionally with a guided 4-7-8 breathing exercise. Use when someone feels sad, anxious, or hopeless.",
  inputSchema: {
    include_breathing: z.boolean().default(false).describe("Also include the 4-7-8 breathing exercise steps.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: ({ include_breathing }) => {
    const message = MESSAGES[Math.floor(Math.random() * MESSAGES.length)];
    const text = include_breathing ? `${message}

A breathing exercise you can try now:
${BREATHING.map((s, i) => `${i + 1}. ${s}`).join("\n")}` : message;
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        message,
        breathing: include_breathing ? BREATHING : null
      }
    };
  }
});

// src/lib/mcp/tools/lead-stats.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.77.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/lead-stats.ts
var lead_stats_default = defineTool2({
  name: "lead_stats",
  title: "Waitlist stats",
  description: "Summarize purelisten waitlist signups: total leads, and how many arrived in the last 7 days. Requires an admin account.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1e3).toISOString();
    const [totalRes, weekRes] = await Promise.all([
      supabase.from("leads").select("id", { count: "exact", head: true }),
      supabase.from("leads").select("id", { count: "exact", head: true }).gte("created_at", since)
    ]);
    if (totalRes.error) throw new ToolError(totalRes.error.message);
    if (weekRes.error) throw new ToolError(weekRes.error.message);
    const stats = {
      total: totalRes.count ?? 0,
      last7Days: weekRes.count ?? 0
    };
    return {
      content: [
        {
          type: "text",
          text: `Total leads: ${stats.total}
Last 7 days: ${stats.last7Days}`
        }
      ],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool3, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_leads_default = defineTool3({
  name: "list_leads",
  title: "List waitlist leads",
  description: "List the most recent waitlist leads (email/phone) captured on purelisten. Requires an admin account.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("How many recent leads to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").select("id, email, phone, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) throw new ToolError2(error.message);
    if (!data || data.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: "No leads visible. Lead access is restricted to admin accounts."
          }
        ],
        structuredContent: { leads: [] }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data }
    };
  }
});

// src/lib/mcp/tools/submit-lead.ts
import { defineTool as defineTool4, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var emailSchema = z3.string().trim().email().max(255);
var phoneSchema = z3.string().trim().regex(/^\+?[1-9]\d{7,14}$/);
var submit_lead_default = defineTool4({
  name: "submit_lead",
  title: "Join the waitlist",
  description: "Add an email address and/or phone number to the purelisten waitlist. At least one contact method is required.",
  inputSchema: {
    email: z3.string().nullable().describe("Email address, or null."),
    phone: z3.string().nullable().describe("Phone number in E.164-ish format (e.g. +14155551234), or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ email, phone }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const cleanEmail = email?.trim() ? emailSchema.safeParse(email) : null;
    const cleanPhone = phone?.trim() ? phoneSchema.safeParse(phone) : null;
    if (cleanEmail && !cleanEmail.success) throw new ToolError3("Invalid email address.");
    if (cleanPhone && !cleanPhone.success) throw new ToolError3("Invalid phone number.");
    if (!cleanEmail && !cleanPhone) {
      throw new ToolError3("Provide at least an email address or a phone number.");
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("leads").insert({
      email: cleanEmail?.success ? cleanEmail.data : null,
      phone: cleanPhone?.success ? cleanPhone.data : null
    });
    if (error) {
      if (error.code === "23505") {
        return {
          content: [{ type: "text", text: "That contact is already on the waitlist." }]
        };
      }
      throw new ToolError3(error.message);
    }
    return { content: [{ type: "text", text: "Added to the purelisten waitlist." }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fzloljyizlkxgwmfbgao";
var mcp_default = defineMcp({
  name: "purelisten",
  title: "purelisten",
  version: "0.1.0",
  instructions: "Tools for purelisten, a service connecting people who need to talk with empathetic listeners. Use `get_comfort` for a gentle grounding message or breathing exercise, `submit_lead` to join the waitlist, and `list_leads` / `lead_stats` for waitlist data (admin accounts only).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_comfort_default, submit_lead_default, list_leads_default, lead_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
